name: Build and Deploy POE2 - Chicken bot

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    env:
      FILENAME: "poe2-chicken-bot"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller poe2-chicken-bot.spec
      shell: cmd

    - name: Create deployment
      uses: softprops/action-gh-release@v2
      with:
        files: dist/poe2-chicken-bot.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
