name: Build and Deploy POE2 - Chicken bot

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy application'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: windows-latest
    env:
      FILENAME: "poe2-chicken-bot"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller poe2-chicken-bot.spec
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: poe2-chicken-bot
        path: dist/poe2-chicken-bot.exe

  deploy:
    needs: build
    runs-on: windows-latest
    if: ${{ github.event_name == 'push' || inputs.deploy == 'true' }}

    steps:
    - name: Download built executable
      uses: actions/download-artifact@v4
      with:
        name: poe2-chicken-bot
        path: dist/

    - name: Create deployment
      uses: softprops/action-gh-release@v2
      with:
        files: dist/poe2-chicken-bot.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
